---
- name: Add Kubernetes apt-key
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key"
    state: present

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    filename: "kubernetes"
    state: present
    update_cache: yes

- name: Install Kubernetes tools (kubeadm, kubelet, kubectl)
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold back Kubernetes packages to prevent automatic upgrades
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    allow_unauthenticated: yes
    force: yes
