---
- name: Add Kubernetes apt-key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
    state: present

- name: Install Kubernetes tools (kubeadm, kubelet, kubectl)
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold back Kubernetes packages to prevent automatic upgrades
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    allow_unauthenticated: yes
    force: yes
